use_frameworks!

target 'TKSecureModule_Example' do
  pod 'TKSecureModule', :path => '../'

  target 'TKSecureModule_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
